"""add unique contraint to columns employee, project, role

Revision ID: a2d8c5857817
Revises: c8e9b53a74d8
Create Date: 2024-10-05 17:11:01.464053

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a2d8c5857817'
down_revision = 'c8e9b53a74d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments') as batch_op:
        batch_op.create_unique_constraint(
            'uq_employee_project_role', ['employee_id', 'project_id', 'role'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments') as batch_op:
        batch_op.drop_constraint('uq_employee_project_role', type_='unique')
    # ### end Alembic commands ###
